# Text shown on the index page.
index_title: Rolandův Receptář
index_description:
  „Ze všech lásek nejupřímnější je láska k jídlu.“

# Whether to show each recipe's image, if available, on the index page. To
# enable, set this option to any non-empty value (other than "false" in recent
# versions of Pandoc). To disable, keep it blank.
show_images_on_index: true

# You can change the content language (really only relevant for hyphenation)
# and related textual labels here.
lang: cz
strings:
  search_placeholder: Hledat...
  uncategorized_label: Bez kategorie
  source_label: Zdroj
  vegan_label: Vegan
  meat_label: Maso
  spicy_label: Pálivé
  sweet_label: Sladké
  salty_label: Slané
  sour_label: Kyselé
  bitter_label: Hořké
  umami_label: Umami
  footer_text: Nechte si chutnat!
  updated_on: Aktualizováno
  edit: Upravit

# If you maintain your recipes in a GitHub repository, you can specify its URL
# here – if non-empty, an "Edit" link will be shown at the bottom of each recipe
# page, referring you to the corresponding Markdown file on GitHub. If you've
# got some sort of continous integration (like the included GitHub Action) set
# up, this effectively turns your site into a wiki.
github_url: https://github.com/schullzroll/recipes

site_author: https://www.linkedin.com/in/roland-schulz/
# Remote for deployment – the value of this setting will be passed to rsync as a
# destination, so you probably want it to look like USER@SERVER:PATH. Make sure
# it's correct – the path in particular – since otherwise stuff that shouldn't
# be deleted or overwritten might indeed be deleted or overwritten!
deploy_remote:
